### ISSUE TITLE
Presence detection endpoint

### ISSUE THREAD

**Issue by TomMini** [robertklep/nefit-easy-core#16]
Hi Robert,

During your reverse engineering of the nefit XMPP communications, did you find some endpoints regarding the presence detection (home/away)?
I'm looking at integrating this in my home-assistant installation but can't find endpoint to let the nefit know I've left home or came back.
Hope you can point me in the right direction. Thanx in advance!

**Comment by robertklep** [comment]
There's an endpoint `/ecus/rrc/homeentrancedetection/userprofile` that suggests it has something to do with presence detection, but since I don't use that feature, I haven't looked at it at all.

Looking at [this page](https://github.com/marcelrv/nefit_easy_protocol/blob/master/homeentrancedetection.md), it seems that that endpoint will return new endpoints that are related to each defined user.

**Comment by TomMini** [comment]
Excellent, that's exactly what I was looking for!!! Thanx very much.

PS. [this repo](https://github.com/TomMini/ha-nefit) is what it's going to end up in.

**Comment by robertklep** [comment]
Nice! I've been playing with HA for a while now, nothing serious at the moment but if I want to start using it more, your component is certainly going to be on the list of needs ;)

Closing this issue, but feel free to ask question if any pop up.
